### ISSUE TITLE
In Internet Explorer the newsletter area is broken

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#19]
![screen shot 2016-01-20 at 10 25 41 am 2](https://cloud.githubusercontent.com/assets/11448089/12458744/33f809aa-bf60-11e5-8241-7bd58a4a7ed2.png)

**Comment by tessguefen** [comment]
Thanks Jenn!

Can you check if it's working now? I added some CSS to fix it.

(Added to structure.css at the bottom. This will only effect IE8):
```
.ie8 .newsletter-input {width: 80%; float:left;}
.ie8  .newsletter-button {width: 20%;}
```
