### ISSUE TITLE
State field Missing is Default country is not US

### ISSUE THREAD

**Issue by bheyde** [mivaecommerce/levels-readytheme#23]
See this thread:

http://www.miva.com/forums/forum/designers-and-developers/readytheme/levels-readytheme/681505-potential-bug-in-checkout-templates?_=1453826266554&_=1453833440641

Can we pass the default country in JS to the /scripts.js file so we don't have to hard code it?

**Comment by tessguefen** [comment]
I found this
```
<mvt:item name="countries" param="ShipCountry"/>
```
I think he is referring to the Other/State Province (we wouldn't have this for US).
I believe that is hidden. See screenshot below:
![Screenshot](http://puu.sh/mLKAc/85b2dff0c3.png)

Do you want to add JS to check what country is selected, and if it's not US, we show it?

**Comment by tessguefen** [comment]
on OCST:
search js-hide, and remove this class.

In readytheme settings (content section readytheme):
Replace this:
```
<script>
var theme_path = "&mvtj:global:theme_path;";
</script>
```
with:
```
<script>
var theme_path = "&mvtj:global:theme_path;";
var default_country = "&mvtj:global:store:country;";
</script>
```

in scripts.js:
find:
```
if( $select.val() === 'US')
```
replace with
```
if( $select.val() === default_country)
```

Also if they want the default estimate shipping "reset" to be with their country..
replace this:
```
$('#js-shipping-estimate-country').val('US');
```
with this:
```
$('#js-shipping-estimate-country').val(default_country);
```

This has been updated in Levels.
