### ISSUE TITLE
Additional Images May not all be visible when going from mobile to tablet

### ISSUE THREAD

**Issue by bheyde** [mivaecommerce/levels-readytheme#24]
See thread here: http://www.miva.com/forums/forum/designers-and-developers/readytheme/levels-readytheme/681565-levels-bug-list?_=1454007208962

**Comment by tessguefen** [comment]
in scripts.js:
Add this new line of code for PROD (right below where slick is being called, look for `$('#js-thumbails').slick`...:
```
$(window).resize( function() {
	$('#js-thumbnails').slickSetOption(null,null,true);
});
```
