### ISSUE TITLE
Issue with Countries Selection

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#30]
When you turn all of the countries off but one in the admin (let's say the US), then go to the store and check out and try and select the drop down menu for countries, it gets stuck and will not allow you to chose the US. It is defaulted on it, but it's greyed out and you can proceed to the next screen. It won't tell you what's wrong, it just gives you an error. (see second attachment)
![country2](https://cloud.githubusercontent.com/assets/11448089/15188465/c28acb24-175a-11e6-92ce-96b19b8a3a81.png)

![error](https://cloud.githubusercontent.com/assets/11448089/15188648/99421fc8-175b-11e6-8004-29fe86693968.png)

**Comment by tessguefen** [comment]
Under jsOCST in scripts.js, add the following:

`$(window).on('load', function () {
			if ($('#ShipCountry:disabled')) {
				$('#ShipCountry').parent().removeClass('no-data');
			}
			if ($('#BillCountry:disabled')) {
				$('#BillCountry').parent().removeClass('no-data');
			}
		});`

Also, update this portion:
`if( $select.val() === default_country){`
To:
`if( $select.val() === default_country || $select.is(':disabled') ){`
