### ISSUE TITLE
JS Error in Quickview when Add to WIshlist is clicked

### ISSUE THREAD

**Issue by bheyde** [mivaecommerce/levels-readytheme#31]
There is a JS error on the CTGY quickview popup when you click add to wishlist, causing the page to take you to the basket page vs the wishlist login page.

This most likely exists on DiVino as well

**Comment by tessguefen** [comment]
PROD >> Quickview content section, look for the form (should only be one). Add the following attribute to the form:
`name="add"`
Should look like this in the end:
`<form method="post" action="&mvte:urls:BASK:auto;" target="_parent" id="js-purchase-product" class="inline-labeling" name="add">`
