### ISSUE TITLE
Mobile View - Subscribe Button cut off

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#35]
I'm not sure if looking at this on my desktop and just sizing it down I've got true mobile size - but the subscription button is too long and is getting cut off. 

![screen shot 2016-08-30 at 10 36 02 am 2](https://cloud.githubusercontent.com/assets/11448089/18099916/94bac682-6e9d-11e6-959d-d4337a55b04f.png)

**Comment by mivajenn** [comment]
![screen shot 2016-09-12 at 10 53 05 am 2](https://cloud.githubusercontent.com/assets/11448089/18446520/7e6e7d30-78d7-11e6-89ec-b0f84130091f.png)

**Comment by influxweb** [comment]
I have corrected the second issue of the buttons not stacking. For the first one, the display and functionality of 'select' elements is a browser-based issue. For the long text you have as the option, that is displaying correctly.
