### ISSUE TITLE
Diners Club and JCB Card Images Missing at checkout

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#36]
![screen shot 2016-08-30 at 10 40 05 am 2](https://cloud.githubusercontent.com/assets/11448089/18100046/29665c9c-6e9e-11e6-909f-08eae12064dc.png)

**Comment by mivajenn** [comment]
Also, not sure why the jcb logo is over to the right vs. on the aligned on the left.

**Comment by influxweb** [comment]
The code has been cleaned up and the other methods removed.
