### ISSUE TITLE
Mobile View - text not aligned in My Account

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#37]
When in mobile view - the first line of the box is moved to the right due to the icon above it. 
![screen shot 2016-08-30 at 10 45 08 am 2](https://cloud.githubusercontent.com/assets/11448089/18100227/ed5d4264-6e9e-11e6-8adb-2d9f24af912a.png)

**Comment by influxweb** [comment]
This has been updated.
