### ISSUE TITLE
Double Colons on product descriptions

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#38]
![screen shot 2016-08-30 at 10 55 58 am 2](https://cloud.githubusercontent.com/assets/11448089/18100699/d4378b12-6ea0-11e6-90be-1ac26500a87e.png)

**Comment by influxweb** [comment]
That is most likely due to the product attribute having a colon at the end of its prompt. Can you confirm if this is the case?

**Comment by mivajenn** [comment]
Yup, that fixed it! Thanks!
