### ISSUE TITLE
When you add a subscription item to cart, subscription terms don't show up

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#46]
Instead you get an error message "Subscription is required for this product."

If you click "Quick View" the terms do show up. Weird!
![screen shot 2016-08-31 at 3 23 38 pm 2](https://cloud.githubusercontent.com/assets/11448089/18148544/09ca322c-6f8f-11e6-9eff-d3ccda722da1.png)

**Comment by influxweb** [comment]
I am unable to duplicate this in the demonstration store. Can you see if you can? http://levels-theme.mivamerchantdev.com/mm5/merchant.mvc?Screen=PROD&Product_Code=subscription_01

**Comment by mivajenn** [comment]
It seems to be working now - something must have corrected it.
