### ISSUE TITLE
Mobile View - Optional Subscription button overlays other buttons

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#47]
On all views across multiple platforms (Safari, Chrome, etc.)

![screen shot 2016-08-31 at 3 28 44 pm 2](https://cloud.githubusercontent.com/assets/11448089/18148634/b33da578-6f8f-11e6-8220-c42b453e56da.png)

![screen shot 2016-08-31 at 3 30 47 pm 2](https://cloud.githubusercontent.com/assets/11448089/18148668/ed76e56a-6f8f-11e6-9545-e5affd623b8e.png)

![screen shot 2016-08-31 at 3 29 53 pm 2](https://cloud.githubusercontent.com/assets/11448089/18148655/d9c732fe-6f8f-11e6-8dc0-d029152526a7.png)

**Comment by influxweb** [comment]
This has been addressed when fixing issue #35
