### ISSUE TITLE
Can't tell if Cancel Subscription is working

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#48]
I cancelled it, and it doesn't seem to show that it's been cancelled. 

The updating worked when I changed subscriptions - but again, can't see any change when I cancelled it.

**Comment by mivajenn** [comment]
Same issue still happening - when you cancel subscription it still shows up under Manage Subscriptions.

**Comment by influxweb** [comment]
This seems to be operating as expected on the demonstration store. Can you test it there to see if you get the same results?

**Comment by mivajenn** [comment]
I would test it, but I can't checkout with an item in my acct. I know MivaPay doesn't work, but when I try and use a credit card outside of MivaPay it gives me this error: An unknown error has occurred
If I don't have a subscription to test with, I can't see if it's working. :-(

**Comment by influxweb** [comment]
I've added subscriptions to your account on the demonstration store through the admin.

**Comment by mivajenn** [comment]
Ok, it worked in your store - so hopefully with the new download it will work in ours!
