### ISSUE TITLE
In Manage Subscriptions it doesn't force you to choose which subscription you want

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#49]
If I purchase an item and decide I want to make it an ongoing subscription - I go to My Account, then Manage Subscriptions, I click on Subscribe and then Add to Cart and it adds it into my cart without making me choose from the Select Subscription drop down menu - so we don't know if I wanted the 6 month, the bi weekly, etc.

**Comment by bheyde** [comment]
Non issue, closing
