### ISSUE TITLE
Managed Saved Cards shows in My Account when MivaPay is enabled

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#51]
When you click on it nothing happens, but I don't think it's supposed to show up when it's been disabled. 
![screen shot 2016-09-12 at 11 02 27 am 2](https://cloud.githubusercontent.com/assets/11448089/18446738/88ed1b80-78d8-11e6-87ce-7e69ae9fdcdf.png)

**Comment by influxweb** [comment]
This has been corrected in issue #39
