### ISSUE TITLE
When editing subscription - I get error message "Invalid Subscription"

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#52]
See before and after screen below
![screen shot 2016-09-12 at 11 08 11 am 2](https://cloud.githubusercontent.com/assets/11448089/18446932/49659784-78d9-11e6-913d-2ceabc7479e7.png)

**Comment by influxweb** [comment]
Does this product have other attributes besides the subscription?

**Comment by mivajenn** [comment]
No, just the subscription drop down. 
![screen shot 2016-09-12 at 1 07 09 pm](https://cloud.githubusercontent.com/assets/11448089/18450933/d4d99580-78e9-11e6-9456-b5e88122a434.png)

**Comment by influxweb** [comment]
That's odd. I'll have to look into what could cause that error message to come up as I haven't seen it yet.
