### ISSUE TITLE
When you cancel subscription under Manage Subscriptions- item is not removed 

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#53]
It worked on your store, but it's not working on Brennan's. Also, I got an email from your store stating the cancellation had been made but on Brennan's store I get an email that says "your subscription has been changed." not cancelled. 
![screen shot 2016-09-12 at 1 47 02 pm 2](https://cloud.githubusercontent.com/assets/11448089/18452369/6d29902e-78ef-11e6-97b9-9a8660d1d843.png)
![Uploading Screen Shot 2016-09-12 at 1.47.08 PM (2).png…]()

**Comment by influxweb** [comment]
You might check that the emails are active. Not sure why one fires one and not the other.
