### ISSUE TITLE
When you cancel subscription under Manage Subscriptions- item is not removed 

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/levels-readytheme#55]
Brennan says there's still a js error - we fixed this on storyteller and he says we should be able to use the same js on Levels.

**Comment by influxweb** [comment]
The JavaScript code on the CSBE page for Levels matches that of Storyteller. Can you post the section of code you have from the 'Subscription Fields' from lines 268-274?

**Comment by bheyde** [comment]
I see the issue here. On levels there is a line break in the JS which is causing issues. Chagne this to \n\n t match storyteller and it should work.

**Comment by bheyde** [comment]
or maybe the framework is converting the \n\n to the line break? Maybe we just kill the line break all together

**Comment by influxweb** [comment]
The code has been updates and should be fine in the next export.
